# Generated by Django 3.2.16 on 2022-11-27 22:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('maintenance', 'Maintenance'), ('repair', 'Repair'), ('misc', 'Misc')], max_length=255)),
                ('kms', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('costs', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
